export const questions = [
  {
    id: 1,
    text: "Quelle est la distance à vol d'oiseau entre Nantes et Oslo ?",
    options: ["1 200 km", "1 500 km", "1 800 km", "2 100 km"],
    correctAnswerIndex: 2,
  },
  {
    id: 2,
    text: "Quelle est la densité de population de la Norvège ? (France : ~119 hab/km²)",
    options: ["14,2 hab/km²", "48,7 hab/km²", "95,3 hab/km²", "191,5 hab/km²"],
    correctAnswerIndex: 0,
  },
  {
    id: 3,
    text: "Combien de ponts traverse-t-on entre Nantes et Copenhague ?",
    options: ["3", "5", "7", "9"],
    correctAnswerIndex: 2,
  },
  {
    id: 4,
    text: "Quel est le plus long tunnel routier du monde, situé en Norvège ?",
    options: [
      "Tunnel de Lærdal (24,5 km)",
      "Tunnel du Fréjus (12,9 km)",
      "Tunnel sous la Manche (50,5 km)",
      "Tunnel de St Bernard (5,8 km)",
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 5,
    text: "Quel pays scandinave compte le plus d'îles ?",
    options: ["Suède", "Norvège", "Finlande", "Danemark"],
    correctAnswerIndex: 1,
  },
  {
    id: 6,
    text: "Comment s'appelle le fameux phénomène de nuit lumineuse en Norvège ?",
    options: [
      "Aurore boréale",
      "Arc-en-ciel lunaire",
      "Nuit polaire",
      "Soleil de minuit",
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 7,
    text: "Quelle est la spécialité culinaire norvégienne à base de poisson fermenté ?",
    options: ["Lutefisk", "Rakfisk", "Surströmming", "Graavilohi"],
    correctAnswerIndex: 1,
  },
  {
    id: 8,
    text: "En quelle année les îles Lofoten sont-elles devenues une destination touristique populaire ?",
    options: ["Années 1880", "Années 1920", "Années 1960", "Années 2000"],
    correctAnswerIndex: 0,
  },
  {
    id: 9,
    text: "Quelle est la vitesse maximale autorisée sur autoroute en Norvège ?",
    options: ["90 km/h", "100 km/h", "110 km/h", "130 km/h"],
    correctAnswerIndex: 1,
  },
  {
    id: 10,
    text: "Quel animal emblématique peut-on observer aux Lofoten ?",
    options: ["Ours polaire", "Renne", "Pygargue à queue blanche", "Loup arctique"],
    correctAnswerIndex: 2,
  },
  {
    id: 11,
    text: "Combien de temps dure la traversée en ferry de Hirtshals (DK) à Kristiansand (NO) ?",
    options: ["1h30", "2h15", "3h", "4h"],
    correctAnswerIndex: 1,
  },
  {
    id: 12,
    text: "Quel est le point culminant de la Norvège ?",
    options: [
      "Glittertind (2 465 m)",
      "Galdhøpiggen (2 469 m)",
      "Mont Blanc (4 809 m)",
      "Kebnekaise (2 097 m)",
    ],
    correctAnswerIndex: 1,
  },
  {
    id: 13,
    text: "Dans quelle ville se trouve la célèbre cathédrale en bois debout (Stavkirke) ?",
    options: ["Oslo", "Bergen", "Stavanger", "Trondheim"],
    correctAnswerIndex: 1,
  },
  {
    id: 14,
    text: "Quel est le surnom d'Oslo ?",
    options: [
      "La ville aux mille sourires",
      "La ville des fjords",
      "La ville des tigres",
      "La ville des vents",
    ],
    correctAnswerIndex: 2,
  },
  {
    id: 15,
    text: "Combien de fois le Gulf Stream réchauffe-t-il les côtes norvégiennes ?",
    options: [
      "Il n'a aucun effet",
      "Environ 2°C",
      "Environ 5°C",
      "Environ 10°C",
    ],
    correctAnswerIndex: 2,
  },
];
